:star: Add update routine
Larra-Quant-Team/DatabaseScripts pull request #1
Opened 2021-01-28 14:44 UTC by fipaniaguaLV

2021-01-29 15:54 UTC, abacklarra commented on update_data_ciq.py
> +            pkl.dump(response_d, file)
Los nombres de los archivos ya no deberian contener la palabra "historical" ya que este codigo no saca historia. Quizas pondría un timestamp y me preocuparía de borrar los archivos acumulados una vez al mes

2021-01-29 15:54 UTC, abacklarra commented on update_data_ciq.py
> +        break
Este break creo que no va en el código final

2021-01-29 15:55 UTC, abacklarra commented on update_data_ciq.py
> +#get_update_properties(str(companies.loc[20, :].name), "Local", daily_fields)
se pueden borrar estos comentarios

2021-01-29 15:55 UTC, abacklarra commented on update_data_ciq.py
> +#                   else 'Valor' for field in quarter}
se pueden borrar estos comentarios

2021-01-29 16:08 UTC, abacklarra commented on update_data_ciq.py
> +    last_id = -1
Este archivo tiene que tener un nombre distinto del que se guarda en la parte anterior (lineas 82 y 115), ya que es el que va a guardar la info de cuanto hemos avanzado con el upload a mongo mientras que el otro es el que guarda el estado del download de ciq. Yo les puse el mismo nombre porque los corrí por separado, pero lo correcto es que sean archivos distintos si se corre todo junto (de lo contrario el código no va a hacer el upload porque el i va a ser igual al id de la ultima empresa).

2021-01-29 16:09 UTC, abacklarra commented on update_data_ciq.py
> +logs = ''
Creo que deberíamos aprovechar de hacer un mejor formato de logs, con un json con entradas para cada empresa. Como está actualmente fue una improvisación a la rápida pero es más difícil de parsear y leer.

2021-01-29 16:10 UTC, abacklarra commented on update_data_ciq.py
> +    with open(dbpath + 'temp/historical_update_response_{}.pkl'.format(id_q),
El mismo comentario anterior de los nombres de estos archivos

2021-01-29 16:11 UTC, abacklarra commented on update_data_ciq.py
> +                #print(series)
podemos borrar estas líneas comentadas

2021-01-29 16:12 UTC, abacklarra commented on update_data_ciq.py
> +        pkl.dump(id_q, file)
mismo comentario de antes, que sea el archivo distinto del save_state de la parte de ciq

2021-01-29 16:12 UTC, abacklarra commented on update_data_ciq.py
> +    break
borrar el break

2021-01-29 16:13 UTC, abacklarra commented on update_data_ciq.py
> +            print('{}. Consultando para {}'.format(i, isin))
recordar hacer esto cada 25 isins

2021-01-29 16:13 UTC, abacklarra commented on update_data_ciq.py
> +        properties_q = get_update_properties(str(id_q), "Local", quarter_fields)
acordarse de cambiar "Local" por "USD" para el paso a producción

2021-01-29 16:15 UTC, abacklarra requested changes
Dejé varios comentarios para corregir previo a hacer el merge

2021-02-01 15:35 UTC, fipaniaguaLV commented on update_data_ciq.py
> +        break
tienes razón

2021-02-01 15:38 UTC, fipaniaguaLV commented on update_data_ciq.py
> +    last_id = -1
tiene un nombre distinto

2021-02-01 15:55 UTC, fipaniaguaLV commented on update_data_ciq.py
> +        properties_q = get_update_properties(str(id_q), "Local", quarter_fields)
esto lo voy a cambiar cuando ya lo suba, por que todavía tengo que probar un par de cosas

2021-02-01 15:55 UTC, merged