Log mailer
Larra-Quant-Team/DatabaseScripts pull request #2
Opened 2021-02-08 15:47 UTC by fipaniaguaLV

2021-02-09 16:15 UTC, abacklarra commented on mailer_quant.py
> +        self.receiver_email = reciber
arreglar typo reciber --> receiver

2021-02-09 16:30 UTC, abacklarra commented on mailer_quant.py
> +            server.sendmail(self.sender_email, reciber, self.text)
agregar linea vacia al final del archivo

2021-02-09 16:31 UTC, abacklarra commented on prettifier.py
> +class HtmlConverter:
agregar los parentesis vacios en la defincion de la clase

2021-02-09 16:38 UTC, abacklarra commented on prettifier.py
> +        self.logs = logs
me llama la atención que sea solo para la data quarter, qué pasa con la daily? por qué? calculamos el tiempo promedio solo con la data quarter? (esta debería ser menos pesada que la daily porque son menos datos, quizás estamos haciendo algo mal)

2021-02-09 16:38 UTC, abacklarra commented on prettifier.py
> +        return
entiendo que el __init__ no requiere return, quizás esto puede generar algun tipo de problema, mejor quitarlo

2021-02-09 16:39 UTC, abacklarra commented on prettifier.py
> +        for companie in self.fields_info:
typo, company es el singular de companies

2021-02-09 16:40 UTC, abacklarra commented on prettifier.py
> +        mail_msg = f"Se a consultado por {self.a_fields} campos"
typo: Se ha

2021-02-09 16:41 UTC, abacklarra commented on prettifier.py
> +        mail_msg += f"- Tiempo prom. de consulta ultimo registro: {self.avg_times_last}\n"
último

2021-02-09 16:46 UTC, abacklarra commented on prettifier.py
> +                Este email se ah generado automáticamente como reporte de la actualización de base de datos mongo
typo "se ha"

2021-02-09 16:47 UTC, abacklarra commented on prettifier.py
> +                    <li> Tiempo prom. de consulta ultimo registro: {self.avg_times_last} </li>
último

2021-02-09 16:47 UTC, abacklarra commented on prettifier.py
> +                Al final de este email se encuentra una tabla que indicá cuantos campos fuerón actualizados correctamente
indica

2021-02-09 20:51 UTC, abacklarra commented on update_data_ciq.py
>                                                          (end.year - start.year)),
Creo que puede haber bugs si end.year - start.year es 0, y en el caso que sea 1 va a pedir los ultimos 4 quarters. Discutámoslo por call

2021-02-09 20:53 UTC, abacklarra commented on update_data_ciq.py
> +        continue
Creo que esto ya no se necesita dado que en las lineas 85 y 86 ya filtras los broken_mnemonics

2021-02-09 20:58 UTC, abacklarra commented on update_data_ciq.py
> +        ciq_log["Time Dump"] = end_time_dump- end_time_request
te recuerdo activar el chequeo de PEP8 en tu editor de código. Aquí falta un espacio antes del signo menos (-)

2021-02-09 20:59 UTC, abacklarra commented on update_data_ciq.py
> +    if id_q % 1 == 0:
cambiar el 1 por un número más grande, hacer print para todos los assets lo hace más lento

2021-02-09 21:04 UTC, abacklarra commented on update_data_ciq.py
> +sleep(1)
es necesario este sleep en el código final?

2021-02-09 21:05 UTC, abacklarra commented on update_data_ciq.py
> +mailer = Mailer("[Acutalización tabla EquityMaster]", mail_msg, mail_html, "fpaniagua@larrainvial.com")
typo: actualización. tmb acuerdate de agregar mi mail y el de martin al pasarlo a produccion (junto con cambiar local por USD)

2021-02-09 21:06 UTC, abacklarra requested changes
Comentarios varios para revisar y corregir. Respecto a funcionalidad, lo más relevante es que conversemos el tema de la data quarter y sus solicitudes a CIQ si end.year - start.year dan algún caso borde (1 año o 0)

2021-02-12 14:48 UTC, fipaniaguaLV commented on prettifier.py
> +        self.logs = logs
No es solo data quarter (en un comienzo lo era), pero ahora se guarda el tiempo dependiendo de si se corrio el programa para daily o quarter. Lo que si tienes razón es que el nombre con que lo estoy guardando en el diccionario ("quarter") induce a confusión

2021-02-12 14:53 UTC, fipaniaguaLV commented on update_data_ciq.py
> +        continue
correcto

2021-02-12 14:56 UTC, fipaniaguaLV commented on update_data_ciq.py
> +sleep(1)
era para asegurarme que todos los archivos están listos para ser enviados por correo, pero no se si sea imprescindible

2021-02-22 14:34 UTC, merged